/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
 */

#ifndef __PLUGINEDITOR_H_C4EEFCBA__
#define __PLUGINEDITOR_H_C4EEFCBA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"




//==============================================================================
/**
 */
class MotionSicknessAudioProcessorEditor  : public AudioProcessorEditor, public Slider::Listener, public ComboBox::Listener
{
public:
    MotionSicknessAudioProcessorEditor (MotionSicknessAudioProcessor* ownerFilter);
    ~MotionSicknessAudioProcessorEditor();
	
	
	void paint (Graphics& g);
    void resized();
    void sliderValueChanged (Slider* sliderThatWasMoved);
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged);
	
    // Binary resources:
    static const char* ahkb_png;
    static const int ahkb_pngSize;
	
	
private:
    //[UserVariables]   -- You can add your own custom variables in this section.
    //[/UserVariables]
	
    //==============================================================================
	MotionSicknessAudioProcessor* processor;

    ScopedPointer<Slider> slider;
    ScopedPointer<Slider> slider2;
    ScopedPointer<Slider> slider3;
    ScopedPointer<ComboBox> comboBox;
    Image cachedImage_ahkb_png;
	
};


#endif  // __PLUGINEDITOR_H_C4EEFCBA__
